//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artem.Data.Access {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Artem.Data.Access.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection reference is null..
        /// </summary>
        internal static string ERR_0 {
            get {
                return ResourceManager.GetString("ERR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection is wrong type &apos;{0}&apos;, when connection of type &apos;{1}&apos; expecting..
        /// </summary>
        internal static string ERR_1 {
            get {
                return ResourceManager.GetString("ERR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database transaction is wrong type &apos;{0}&apos;, when transaction of type &apos;{1}&apos; expecting..
        /// </summary>
        internal static string ERR_100 {
            get {
                return ResourceManager.GetString("ERR_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access configuration section not found in the config file..
        /// </summary>
        internal static string ERR_1000 {
            get {
                return ResourceManager.GetString("ERR_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction can not be started when database is in a scope!.
        /// </summary>
        internal static string ERR_101 {
            get {
                return ResourceManager.GetString("ERR_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection name &apos;{0}&apos; was not found in the applications configuration or the connection string is empty..
        /// </summary>
        internal static string ERR_2 {
            get {
                return ResourceManager.GetString("ERR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command type &apos;{0}&apos; is not a correct command type. Please use: &apos;StoredProcedure&apos;, &apos;TableDirect&apos; or &apos;Text&apos;..
        /// </summary>
        internal static string ERR_200 {
            get {
                return ResourceManager.GetString("ERR_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseScopes can not be nested!.
        /// </summary>
        internal static string ERR_500 {
            get {
                return ResourceManager.GetString("ERR_500", resourceCulture);
            }
        }
    }
}
